name: delivery_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  consumer: ^2.3.1
  provider: ^6.1.2
  date_format: ^2.0.9
  intl: ^0.20.0
  supabase_flutter: ^2.8.1
  flutter_launcher_icons: ^0.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
 

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/delivery.jpeg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/delivery.jpeg"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/delivery.jpeg"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/delivery.jpeg"

flutter:
  uses-material-design: true
  assets:
    - assets/
   
